<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <DebugType>embedded</DebugType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <!-- 核心公共依赖 -->
        <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.735" ExcludeAssets="runtime;native" />
        <PackageReference Include="BepInEx.AutoPlugin" Version="1.1.0" PrivateAssets="all" />
        <!-- 在 .csproj 的 ItemGroup 标签里加上这一行 -->
        <Reference Include="UnityEngine.InputLegacyModule">
            <HintPath>libs\UnityEngine.InputLegacyModule.dll</HintPath>
        </Reference>
        <!-- 引入你本地 libs 文件夹里的所有核心 DLL -->
        <Reference Include="Il2Cppmscorlib">
            <HintPath>libs\Il2Cppmscorlib.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine">
            <HintPath>libs\UnityEngine.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>libs\UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>libs\UnityEngine.UI.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TextRenderingModule">
            <HintPath>libs\UnityEngine.TextRenderingModule.dll</HintPath>
        </Reference>
        <Reference Include="Unity.TextMeshPro">
            <HintPath>libs\Unity.TextMeshPro.dll</HintPath>
        </Reference>
        <Reference Include="Assembly-CSharp">
            <HintPath>libs\Assembly-CSharp.dll</HintPath>
        </Reference>
        <Reference Include="0Harmony">
            <HintPath>libs\0Harmony.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ImageConversionModule">
            <HintPath>libs\UnityEngine.ImageConversionModule.dll</HintPath>
        </Reference>
        <Reference Include="Hazel">
            <HintPath>libs\Hazel.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.IMGUIModule">
    <HintPath>libs\UnityEngine.IMGUIModule.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>